return {
  -- {
  --   "mikavilpas/yazi.nvim",
  --   event = "VeryLazy",
  --   keys = {
  --     {
  --       "<leader>e",
  --       "<Cmd>Yazi<CR>",
  --       desc = "Open file manager",
  --     },
  --     {
  --       "<leader>E",
  --       "<Cmd>Yazi cwd<CR>",
  --       desc = "Open file manager in nvim's working directory",
  --     },
  --   },
  --   opts = {
  --     -- if you want to open yazi instead of netrw, see below for more info
  --     open_for_directories = false,
  --   },
  -- },
}
